version: "3.8"

services: 
  nginx:
    image: nginx:1.19-alpine
    container_name: site-nginx
    ports: 
      - 8080:80
    volumes:
      - /home/dhoz/Documents/Containers/Nginx-php/site/public:/usr/share/nginx/html
      - /home/dhoz/Documents/Containers/Nginx-php/docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    volumes: 
      - /home/dhoz/Documents/Containers/Nginx-php/site/public:/usr/share/nginx/html
    links: 
     - db

  db:
    image: mysql:5.7.22
    container_name: db
    environment: 
      MYSQL_DATABASE: serverglpi
      MYSQL_ROOT_PASSWORD: root2021
    ports: 
      - "3306:3306"
    volumes: 
      - database:/var/lib/mysql

volumes:
  database:
    driver: local
    
