version: '2'

services:
  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    ports:
      - 139:130
      - 445:445
    volumes: 
      - /usr/share/zoneinfo/America/Bogota;/etc/localtime
      - /home/dhoz/Documents/Containers/DownTorrents/pi/media;/media
      - /home/dhoz/Documents/Containers/DownTorrents/pi/downloads:/downloads

  rtorrent:
    image: pablokbs/rutorrent-armhf
    ports: 
      - 80:80
      - 51413:51413
      - 6881:6881/udp
    volumes: 
      - /home/dhoz/Documents/Containers/DownTorrents/pi/torrents-config/rtorrent:/config/rtorrent
      - /home/dhoz/Documents/Containers/DownTorrents/pi/downloads:/downloads
    restart: always
    networks: 
      lan:
        ipv4_address: 192.168.0.5

networks: 
  lan:
    driver: macvlan
    driver_opts: 
      parent: enp0s3
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"